// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: mapsvr/bigmapmarch.proto

package mapsvr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	types "pitaya-game/protos/protobuf/pb/golang/common/types"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TroopType int32

const (
	TroopType_TROOP_TYPE_UNSPECIFIED TroopType = 0
	TroopType_INFANTRY               TroopType = 1 // 步兵
	TroopType_CAVALRY                TroopType = 2 // 骑兵
	TroopType_ARCHER                 TroopType = 3 // 弓兵
)

// Enum value maps for TroopType.
var (
	TroopType_name = map[int32]string{
		0: "TROOP_TYPE_UNSPECIFIED",
		1: "INFANTRY",
		2: "CAVALRY",
		3: "ARCHER",
	}
	TroopType_value = map[string]int32{
		"TROOP_TYPE_UNSPECIFIED": 0,
		"INFANTRY":               1,
		"CAVALRY":                2,
		"ARCHER":                 3,
	}
)

func (x TroopType) Enum() *TroopType {
	p := new(TroopType)
	*p = x
	return p
}

func (x TroopType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TroopType) Descriptor() protoreflect.EnumDescriptor {
	return file_mapsvr_bigmapmarch_proto_enumTypes[0].Descriptor()
}

func (TroopType) Type() protoreflect.EnumType {
	return &file_mapsvr_bigmapmarch_proto_enumTypes[0]
}

func (x TroopType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TroopType.Descriptor instead.
func (TroopType) EnumDescriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{0}
}

type MarchType int32

const (
	MarchType_MARCH_TYPE_UNSPECIFIED MarchType = 0
	MarchType_MARCH_TYPE_ATTACK      MarchType = 1 // 出征攻击
	MarchType_MARCH_TYPE_GATHER      MarchType = 2 // 采集资源
	MarchType_MARCH_TYPE_SCOUT       MarchType = 3 // 侦察
	MarchType_MARCH_TYPE_RALLY       MarchType = 4 // 集结（参与者）
	MarchType_MARCH_TYPE_REINFORCE   MarchType = 5 // 援军驻防
	MarchType_MARCH_TYPE_RETURN      MarchType = 6 // 回城
	MarchType_MARCH_TYPE_RALLY_LEAD  MarchType = 7 // 集结发起者
)

// Enum value maps for MarchType.
var (
	MarchType_name = map[int32]string{
		0: "MARCH_TYPE_UNSPECIFIED",
		1: "MARCH_TYPE_ATTACK",
		2: "MARCH_TYPE_GATHER",
		3: "MARCH_TYPE_SCOUT",
		4: "MARCH_TYPE_RALLY",
		5: "MARCH_TYPE_REINFORCE",
		6: "MARCH_TYPE_RETURN",
		7: "MARCH_TYPE_RALLY_LEAD",
	}
	MarchType_value = map[string]int32{
		"MARCH_TYPE_UNSPECIFIED": 0,
		"MARCH_TYPE_ATTACK":      1,
		"MARCH_TYPE_GATHER":      2,
		"MARCH_TYPE_SCOUT":       3,
		"MARCH_TYPE_RALLY":       4,
		"MARCH_TYPE_REINFORCE":   5,
		"MARCH_TYPE_RETURN":      6,
		"MARCH_TYPE_RALLY_LEAD":  7,
	}
)

func (x MarchType) Enum() *MarchType {
	p := new(MarchType)
	*p = x
	return p
}

func (x MarchType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MarchType) Descriptor() protoreflect.EnumDescriptor {
	return file_mapsvr_bigmapmarch_proto_enumTypes[1].Descriptor()
}

func (MarchType) Type() protoreflect.EnumType {
	return &file_mapsvr_bigmapmarch_proto_enumTypes[1]
}

func (x MarchType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MarchType.Descriptor instead.
func (MarchType) EnumDescriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{1}
}

type MarchState int32

const (
	MarchState_MARCH_STATE_UNSPECIFIED MarchState = 0
	MarchState_MARCH_STATE_MARCHING    MarchState = 1 // 行进中
	MarchState_MARCH_STATE_FIGHTING    MarchState = 2 // 战斗中
	MarchState_MARCH_STATE_GATHERING   MarchState = 3 // 采集中
	MarchState_MARCH_STATE_STATIONED   MarchState = 4 // 驻防中
	MarchState_MARCH_STATE_SCOUTING    MarchState = 5 // 侦察中
	MarchState_MARCH_STATE_RETURNING   MarchState = 6 // 返回中
)

// Enum value maps for MarchState.
var (
	MarchState_name = map[int32]string{
		0: "MARCH_STATE_UNSPECIFIED",
		1: "MARCH_STATE_MARCHING",
		2: "MARCH_STATE_FIGHTING",
		3: "MARCH_STATE_GATHERING",
		4: "MARCH_STATE_STATIONED",
		5: "MARCH_STATE_SCOUTING",
		6: "MARCH_STATE_RETURNING",
	}
	MarchState_value = map[string]int32{
		"MARCH_STATE_UNSPECIFIED": 0,
		"MARCH_STATE_MARCHING":    1,
		"MARCH_STATE_FIGHTING":    2,
		"MARCH_STATE_GATHERING":   3,
		"MARCH_STATE_STATIONED":   4,
		"MARCH_STATE_SCOUTING":    5,
		"MARCH_STATE_RETURNING":   6,
	}
)

func (x MarchState) Enum() *MarchState {
	p := new(MarchState)
	*p = x
	return p
}

func (x MarchState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MarchState) Descriptor() protoreflect.EnumDescriptor {
	return file_mapsvr_bigmapmarch_proto_enumTypes[2].Descriptor()
}

func (MarchState) Type() protoreflect.EnumType {
	return &file_mapsvr_bigmapmarch_proto_enumTypes[2]
}

func (x MarchState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MarchState.Descriptor instead.
func (MarchState) EnumDescriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{2}
}

type TargetType int32

const (
	TargetType_TARGET_TYPE_UNSPECIFIED TargetType = 0
	TargetType_TARGET_TYPE_PLAYER_CITY TargetType = 1 // 玩家城池
	TargetType_TARGET_TYPE_MONSTER     TargetType = 2 // 野怪
	TargetType_TARGET_TYPE_RESOURCE    TargetType = 3 // 资源点
	TargetType_TARGET_TYPE_ALLIANCE    TargetType = 4 // 联盟建筑
)

// Enum value maps for TargetType.
var (
	TargetType_name = map[int32]string{
		0: "TARGET_TYPE_UNSPECIFIED",
		1: "TARGET_TYPE_PLAYER_CITY",
		2: "TARGET_TYPE_MONSTER",
		3: "TARGET_TYPE_RESOURCE",
		4: "TARGET_TYPE_ALLIANCE",
	}
	TargetType_value = map[string]int32{
		"TARGET_TYPE_UNSPECIFIED": 0,
		"TARGET_TYPE_PLAYER_CITY": 1,
		"TARGET_TYPE_MONSTER":     2,
		"TARGET_TYPE_RESOURCE":    3,
		"TARGET_TYPE_ALLIANCE":    4,
	}
)

func (x TargetType) Enum() *TargetType {
	p := new(TargetType)
	*p = x
	return p
}

func (x TargetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TargetType) Descriptor() protoreflect.EnumDescriptor {
	return file_mapsvr_bigmapmarch_proto_enumTypes[3].Descriptor()
}

func (TargetType) Type() protoreflect.EnumType {
	return &file_mapsvr_bigmapmarch_proto_enumTypes[3]
}

func (x TargetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TargetType.Descriptor instead.
func (TargetType) EnumDescriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{3}
}

type RallyState int32

const (
	RallyState_RALLY_STATE_UNSPECIFIED RallyState = 0
	RallyState_RALLY_STATE_WAITING     RallyState = 1 // 等待成员加入
	RallyState_RALLY_STATE_MARCHING    RallyState = 2 // 集结行军中
	RallyState_RALLY_STATE_FIGHTING    RallyState = 3 // 战斗中
	RallyState_RALLY_STATE_ENDED       RallyState = 4 // 已结束
)

// Enum value maps for RallyState.
var (
	RallyState_name = map[int32]string{
		0: "RALLY_STATE_UNSPECIFIED",
		1: "RALLY_STATE_WAITING",
		2: "RALLY_STATE_MARCHING",
		3: "RALLY_STATE_FIGHTING",
		4: "RALLY_STATE_ENDED",
	}
	RallyState_value = map[string]int32{
		"RALLY_STATE_UNSPECIFIED": 0,
		"RALLY_STATE_WAITING":     1,
		"RALLY_STATE_MARCHING":    2,
		"RALLY_STATE_FIGHTING":    3,
		"RALLY_STATE_ENDED":       4,
	}
)

func (x RallyState) Enum() *RallyState {
	p := new(RallyState)
	*p = x
	return p
}

func (x RallyState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RallyState) Descriptor() protoreflect.EnumDescriptor {
	return file_mapsvr_bigmapmarch_proto_enumTypes[4].Descriptor()
}

func (RallyState) Type() protoreflect.EnumType {
	return &file_mapsvr_bigmapmarch_proto_enumTypes[4]
}

func (x RallyState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RallyState.Descriptor instead.
func (RallyState) EnumDescriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{4}
}

type TroopLevels struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LevelCounts   map[int32]int32        `protobuf:"bytes,1,rep,name=level_counts,json=levelCounts,proto3" json:"level_counts,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // level -> count
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TroopLevels) Reset() {
	*x = TroopLevels{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TroopLevels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TroopLevels) ProtoMessage() {}

func (x *TroopLevels) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TroopLevels.ProtoReflect.Descriptor instead.
func (*TroopLevels) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{0}
}

func (x *TroopLevels) GetLevelCounts() map[int32]int32 {
	if x != nil {
		return x.LevelCounts
	}
	return nil
}

type MarchInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarchId       int64                  `protobuf:"varint,1,opt,name=march_id,json=marchId,proto3" json:"march_id,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MarchType     MarchType              `protobuf:"varint,3,opt,name=march_type,json=marchType,proto3,enum=mapsvr.MarchType" json:"march_type,omitempty"`
	State         MarchState             `protobuf:"varint,4,opt,name=state,proto3,enum=mapsvr.MarchState" json:"state,omitempty"`
	FromPos       *Position              `protobuf:"bytes,5,opt,name=from_pos,json=fromPos,proto3" json:"from_pos,omitempty"`
	ToPos         *Position              `protobuf:"bytes,6,opt,name=to_pos,json=toPos,proto3" json:"to_pos,omitempty"`
	StartAt       int64                  `protobuf:"varint,7,opt,name=start_at,json=startAt,proto3" json:"start_at,omitempty"`    // 出发时间戳（秒）
	ArriveAt      int64                  `protobuf:"varint,8,opt,name=arrive_at,json=arriveAt,proto3" json:"arrive_at,omitempty"` // 预计到达时间戳（秒）
	TargetType    TargetType             `protobuf:"varint,9,opt,name=target_type,json=targetType,proto3,enum=mapsvr.TargetType" json:"target_type,omitempty"`
	TargetId      int64                  `protobuf:"varint,10,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	HeroIds       []int64                `protobuf:"varint,11,rep,packed,name=hero_ids,json=heroIds,proto3" json:"hero_ids,omitempty"`
	Troops        map[int32]*TroopLevels `protobuf:"bytes,12,rep,name=troops,proto3" json:"troops,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // TroopType(int32) -> TroopLevels
	RallyId       int64                  `protobuf:"varint,13,opt,name=rally_id,json=rallyId,proto3" json:"rally_id,omitempty"`                                                          // 所属集结 ID, 0 表示非集结
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarchInfo) Reset() {
	*x = MarchInfo{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarchInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarchInfo) ProtoMessage() {}

func (x *MarchInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarchInfo.ProtoReflect.Descriptor instead.
func (*MarchInfo) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{1}
}

func (x *MarchInfo) GetMarchId() int64 {
	if x != nil {
		return x.MarchId
	}
	return 0
}

func (x *MarchInfo) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *MarchInfo) GetMarchType() MarchType {
	if x != nil {
		return x.MarchType
	}
	return MarchType_MARCH_TYPE_UNSPECIFIED
}

func (x *MarchInfo) GetState() MarchState {
	if x != nil {
		return x.State
	}
	return MarchState_MARCH_STATE_UNSPECIFIED
}

func (x *MarchInfo) GetFromPos() *Position {
	if x != nil {
		return x.FromPos
	}
	return nil
}

func (x *MarchInfo) GetToPos() *Position {
	if x != nil {
		return x.ToPos
	}
	return nil
}

func (x *MarchInfo) GetStartAt() int64 {
	if x != nil {
		return x.StartAt
	}
	return 0
}

func (x *MarchInfo) GetArriveAt() int64 {
	if x != nil {
		return x.ArriveAt
	}
	return 0
}

func (x *MarchInfo) GetTargetType() TargetType {
	if x != nil {
		return x.TargetType
	}
	return TargetType_TARGET_TYPE_UNSPECIFIED
}

func (x *MarchInfo) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *MarchInfo) GetHeroIds() []int64 {
	if x != nil {
		return x.HeroIds
	}
	return nil
}

func (x *MarchInfo) GetTroops() map[int32]*TroopLevels {
	if x != nil {
		return x.Troops
	}
	return nil
}

func (x *MarchInfo) GetRallyId() int64 {
	if x != nil {
		return x.RallyId
	}
	return 0
}

type RallyMemberInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Troops        map[int32]*TroopLevels `protobuf:"bytes,2,rep,name=troops,proto3" json:"troops,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	HeroIds       []int64                `protobuf:"varint,3,rep,packed,name=hero_ids,json=heroIds,proto3" json:"hero_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RallyMemberInfo) Reset() {
	*x = RallyMemberInfo{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RallyMemberInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RallyMemberInfo) ProtoMessage() {}

func (x *RallyMemberInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RallyMemberInfo.ProtoReflect.Descriptor instead.
func (*RallyMemberInfo) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{2}
}

func (x *RallyMemberInfo) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *RallyMemberInfo) GetTroops() map[int32]*TroopLevels {
	if x != nil {
		return x.Troops
	}
	return nil
}

func (x *RallyMemberInfo) GetHeroIds() []int64 {
	if x != nil {
		return x.HeroIds
	}
	return nil
}

type RallyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RallyId       int64                  `protobuf:"varint,1,opt,name=rally_id,json=rallyId,proto3" json:"rally_id,omitempty"`
	LeaderId      string                 `protobuf:"bytes,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	AllianceId    string                 `protobuf:"bytes,3,opt,name=alliance_id,json=allianceId,proto3" json:"alliance_id,omitempty"`
	TargetPos     *Position              `protobuf:"bytes,4,opt,name=target_pos,json=targetPos,proto3" json:"target_pos,omitempty"`
	TargetType    TargetType             `protobuf:"varint,5,opt,name=target_type,json=targetType,proto3,enum=mapsvr.TargetType" json:"target_type,omitempty"`
	TargetId      int64                  `protobuf:"varint,6,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	MaxCapacity   int64                  `protobuf:"varint,7,opt,name=max_capacity,json=maxCapacity,proto3" json:"max_capacity,omitempty"`
	CreateAt      int64                  `protobuf:"varint,8,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	LaunchAt      int64                  `protobuf:"varint,9,opt,name=launch_at,json=launchAt,proto3" json:"launch_at,omitempty"` // 预计发起时间
	State         RallyState             `protobuf:"varint,10,opt,name=state,proto3,enum=mapsvr.RallyState" json:"state,omitempty"`
	Members       []*RallyMemberInfo     `protobuf:"bytes,11,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RallyInfo) Reset() {
	*x = RallyInfo{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RallyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RallyInfo) ProtoMessage() {}

func (x *RallyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RallyInfo.ProtoReflect.Descriptor instead.
func (*RallyInfo) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{3}
}

func (x *RallyInfo) GetRallyId() int64 {
	if x != nil {
		return x.RallyId
	}
	return 0
}

func (x *RallyInfo) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *RallyInfo) GetAllianceId() string {
	if x != nil {
		return x.AllianceId
	}
	return ""
}

func (x *RallyInfo) GetTargetPos() *Position {
	if x != nil {
		return x.TargetPos
	}
	return nil
}

func (x *RallyInfo) GetTargetType() TargetType {
	if x != nil {
		return x.TargetType
	}
	return TargetType_TARGET_TYPE_UNSPECIFIED
}

func (x *RallyInfo) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *RallyInfo) GetMaxCapacity() int64 {
	if x != nil {
		return x.MaxCapacity
	}
	return 0
}

func (x *RallyInfo) GetCreateAt() int64 {
	if x != nil {
		return x.CreateAt
	}
	return 0
}

func (x *RallyInfo) GetLaunchAt() int64 {
	if x != nil {
		return x.LaunchAt
	}
	return 0
}

func (x *RallyInfo) GetState() RallyState {
	if x != nil {
		return x.State
	}
	return RallyState_RALLY_STATE_UNSPECIFIED
}

func (x *RallyInfo) GetMembers() []*RallyMemberInfo {
	if x != nil {
		return x.Members
	}
	return nil
}

type StartMarchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarchType     MarchType              `protobuf:"varint,1,opt,name=march_type,json=marchType,proto3,enum=mapsvr.MarchType" json:"march_type,omitempty"`
	ToPos         *Position              `protobuf:"bytes,2,opt,name=to_pos,json=toPos,proto3" json:"to_pos,omitempty"`
	TargetType    TargetType             `protobuf:"varint,3,opt,name=target_type,json=targetType,proto3,enum=mapsvr.TargetType" json:"target_type,omitempty"`
	TargetId      int64                  `protobuf:"varint,4,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	HeroIds       []int64                `protobuf:"varint,5,rep,packed,name=hero_ids,json=heroIds,proto3" json:"hero_ids,omitempty"`
	Troops        map[int32]*TroopLevels `protobuf:"bytes,6,rep,name=troops,proto3" json:"troops,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartMarchRequest) Reset() {
	*x = StartMarchRequest{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartMarchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMarchRequest) ProtoMessage() {}

func (x *StartMarchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMarchRequest.ProtoReflect.Descriptor instead.
func (*StartMarchRequest) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{4}
}

func (x *StartMarchRequest) GetMarchType() MarchType {
	if x != nil {
		return x.MarchType
	}
	return MarchType_MARCH_TYPE_UNSPECIFIED
}

func (x *StartMarchRequest) GetToPos() *Position {
	if x != nil {
		return x.ToPos
	}
	return nil
}

func (x *StartMarchRequest) GetTargetType() TargetType {
	if x != nil {
		return x.TargetType
	}
	return TargetType_TARGET_TYPE_UNSPECIFIED
}

func (x *StartMarchRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *StartMarchRequest) GetHeroIds() []int64 {
	if x != nil {
		return x.HeroIds
	}
	return nil
}

func (x *StartMarchRequest) GetTroops() map[int32]*TroopLevels {
	if x != nil {
		return x.Troops
	}
	return nil
}

type StartMarchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *types.CommonResp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	March         *MarchInfo             `protobuf:"bytes,2,opt,name=march,proto3" json:"march,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartMarchResponse) Reset() {
	*x = StartMarchResponse{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartMarchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMarchResponse) ProtoMessage() {}

func (x *StartMarchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMarchResponse.ProtoReflect.Descriptor instead.
func (*StartMarchResponse) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{5}
}

func (x *StartMarchResponse) GetResp() *types.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *StartMarchResponse) GetMarch() *MarchInfo {
	if x != nil {
		return x.March
	}
	return nil
}

type CancelMarchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarchId       int64                  `protobuf:"varint,1,opt,name=march_id,json=marchId,proto3" json:"march_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelMarchRequest) Reset() {
	*x = CancelMarchRequest{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelMarchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelMarchRequest) ProtoMessage() {}

func (x *CancelMarchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelMarchRequest.ProtoReflect.Descriptor instead.
func (*CancelMarchRequest) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{6}
}

func (x *CancelMarchRequest) GetMarchId() int64 {
	if x != nil {
		return x.MarchId
	}
	return 0
}

type CancelMarchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *types.CommonResp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelMarchResponse) Reset() {
	*x = CancelMarchResponse{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelMarchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelMarchResponse) ProtoMessage() {}

func (x *CancelMarchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelMarchResponse.ProtoReflect.Descriptor instead.
func (*CancelMarchResponse) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{7}
}

func (x *CancelMarchResponse) GetResp() *types.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

type SpeedUpMarchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarchId       int64                  `protobuf:"varint,1,opt,name=march_id,json=marchId,proto3" json:"march_id,omitempty"`
	ItemId        int32                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemNum       int32                  `protobuf:"varint,3,opt,name=item_num,json=itemNum,proto3" json:"item_num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpeedUpMarchRequest) Reset() {
	*x = SpeedUpMarchRequest{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeedUpMarchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeedUpMarchRequest) ProtoMessage() {}

func (x *SpeedUpMarchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeedUpMarchRequest.ProtoReflect.Descriptor instead.
func (*SpeedUpMarchRequest) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{8}
}

func (x *SpeedUpMarchRequest) GetMarchId() int64 {
	if x != nil {
		return x.MarchId
	}
	return 0
}

func (x *SpeedUpMarchRequest) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *SpeedUpMarchRequest) GetItemNum() int32 {
	if x != nil {
		return x.ItemNum
	}
	return 0
}

type SpeedUpMarchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *types.CommonResp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	NewArriveAt   int64                  `protobuf:"varint,2,opt,name=new_arrive_at,json=newArriveAt,proto3" json:"new_arrive_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpeedUpMarchResponse) Reset() {
	*x = SpeedUpMarchResponse{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpeedUpMarchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpeedUpMarchResponse) ProtoMessage() {}

func (x *SpeedUpMarchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpeedUpMarchResponse.ProtoReflect.Descriptor instead.
func (*SpeedUpMarchResponse) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{9}
}

func (x *SpeedUpMarchResponse) GetResp() *types.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *SpeedUpMarchResponse) GetNewArriveAt() int64 {
	if x != nil {
		return x.NewArriveAt
	}
	return 0
}

type CreateRallyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetPos     *Position              `protobuf:"bytes,1,opt,name=target_pos,json=targetPos,proto3" json:"target_pos,omitempty"`
	TargetType    TargetType             `protobuf:"varint,2,opt,name=target_type,json=targetType,proto3,enum=mapsvr.TargetType" json:"target_type,omitempty"`
	TargetId      int64                  `protobuf:"varint,3,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	WaitDuration  int64                  `protobuf:"varint,4,opt,name=wait_duration,json=waitDuration,proto3" json:"wait_duration,omitempty"` // 等待时间（秒）
	HeroIds       []int64                `protobuf:"varint,5,rep,packed,name=hero_ids,json=heroIds,proto3" json:"hero_ids,omitempty"`
	Troops        map[int32]*TroopLevels `protobuf:"bytes,6,rep,name=troops,proto3" json:"troops,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRallyRequest) Reset() {
	*x = CreateRallyRequest{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRallyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRallyRequest) ProtoMessage() {}

func (x *CreateRallyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRallyRequest.ProtoReflect.Descriptor instead.
func (*CreateRallyRequest) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{10}
}

func (x *CreateRallyRequest) GetTargetPos() *Position {
	if x != nil {
		return x.TargetPos
	}
	return nil
}

func (x *CreateRallyRequest) GetTargetType() TargetType {
	if x != nil {
		return x.TargetType
	}
	return TargetType_TARGET_TYPE_UNSPECIFIED
}

func (x *CreateRallyRequest) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *CreateRallyRequest) GetWaitDuration() int64 {
	if x != nil {
		return x.WaitDuration
	}
	return 0
}

func (x *CreateRallyRequest) GetHeroIds() []int64 {
	if x != nil {
		return x.HeroIds
	}
	return nil
}

func (x *CreateRallyRequest) GetTroops() map[int32]*TroopLevels {
	if x != nil {
		return x.Troops
	}
	return nil
}

type CreateRallyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *types.CommonResp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	Rally         *RallyInfo             `protobuf:"bytes,2,opt,name=rally,proto3" json:"rally,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRallyResponse) Reset() {
	*x = CreateRallyResponse{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRallyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRallyResponse) ProtoMessage() {}

func (x *CreateRallyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRallyResponse.ProtoReflect.Descriptor instead.
func (*CreateRallyResponse) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{11}
}

func (x *CreateRallyResponse) GetResp() *types.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *CreateRallyResponse) GetRally() *RallyInfo {
	if x != nil {
		return x.Rally
	}
	return nil
}

type JoinRallyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RallyId       int64                  `protobuf:"varint,1,opt,name=rally_id,json=rallyId,proto3" json:"rally_id,omitempty"`
	HeroIds       []int64                `protobuf:"varint,2,rep,packed,name=hero_ids,json=heroIds,proto3" json:"hero_ids,omitempty"`
	Troops        map[int32]*TroopLevels `protobuf:"bytes,3,rep,name=troops,proto3" json:"troops,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRallyRequest) Reset() {
	*x = JoinRallyRequest{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRallyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRallyRequest) ProtoMessage() {}

func (x *JoinRallyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRallyRequest.ProtoReflect.Descriptor instead.
func (*JoinRallyRequest) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{12}
}

func (x *JoinRallyRequest) GetRallyId() int64 {
	if x != nil {
		return x.RallyId
	}
	return 0
}

func (x *JoinRallyRequest) GetHeroIds() []int64 {
	if x != nil {
		return x.HeroIds
	}
	return nil
}

func (x *JoinRallyRequest) GetTroops() map[int32]*TroopLevels {
	if x != nil {
		return x.Troops
	}
	return nil
}

type JoinRallyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *types.CommonResp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRallyResponse) Reset() {
	*x = JoinRallyResponse{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRallyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRallyResponse) ProtoMessage() {}

func (x *JoinRallyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRallyResponse.ProtoReflect.Descriptor instead.
func (*JoinRallyResponse) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{13}
}

func (x *JoinRallyResponse) GetResp() *types.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

type LaunchRallyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RallyId       int64                  `protobuf:"varint,1,opt,name=rally_id,json=rallyId,proto3" json:"rally_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchRallyRequest) Reset() {
	*x = LaunchRallyRequest{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchRallyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchRallyRequest) ProtoMessage() {}

func (x *LaunchRallyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchRallyRequest.ProtoReflect.Descriptor instead.
func (*LaunchRallyRequest) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{14}
}

func (x *LaunchRallyRequest) GetRallyId() int64 {
	if x != nil {
		return x.RallyId
	}
	return 0
}

type LaunchRallyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *types.CommonResp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchRallyResponse) Reset() {
	*x = LaunchRallyResponse{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchRallyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchRallyResponse) ProtoMessage() {}

func (x *LaunchRallyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchRallyResponse.ProtoReflect.Descriptor instead.
func (*LaunchRallyResponse) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{15}
}

func (x *LaunchRallyResponse) GetResp() *types.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

type CancelRallyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RallyId       int64                  `protobuf:"varint,1,opt,name=rally_id,json=rallyId,proto3" json:"rally_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRallyRequest) Reset() {
	*x = CancelRallyRequest{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRallyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRallyRequest) ProtoMessage() {}

func (x *CancelRallyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRallyRequest.ProtoReflect.Descriptor instead.
func (*CancelRallyRequest) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{16}
}

func (x *CancelRallyRequest) GetRallyId() int64 {
	if x != nil {
		return x.RallyId
	}
	return 0
}

type CancelRallyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *types.CommonResp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRallyResponse) Reset() {
	*x = CancelRallyResponse{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRallyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRallyResponse) ProtoMessage() {}

func (x *CancelRallyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRallyResponse.ProtoReflect.Descriptor instead.
func (*CancelRallyResponse) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{17}
}

func (x *CancelRallyResponse) GetResp() *types.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

type MarchCreateNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	March         *MarchInfo             `protobuf:"bytes,1,opt,name=march,proto3" json:"march,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarchCreateNotify) Reset() {
	*x = MarchCreateNotify{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarchCreateNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarchCreateNotify) ProtoMessage() {}

func (x *MarchCreateNotify) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarchCreateNotify.ProtoReflect.Descriptor instead.
func (*MarchCreateNotify) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{18}
}

func (x *MarchCreateNotify) GetMarch() *MarchInfo {
	if x != nil {
		return x.March
	}
	return nil
}

type MarchStateNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	March         *MarchInfo             `protobuf:"bytes,1,opt,name=march,proto3" json:"march,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarchStateNotify) Reset() {
	*x = MarchStateNotify{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarchStateNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarchStateNotify) ProtoMessage() {}

func (x *MarchStateNotify) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarchStateNotify.ProtoReflect.Descriptor instead.
func (*MarchStateNotify) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{19}
}

func (x *MarchStateNotify) GetMarch() *MarchInfo {
	if x != nil {
		return x.March
	}
	return nil
}

type MarchRemoveNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarchId       int64                  `protobuf:"varint,1,opt,name=march_id,json=marchId,proto3" json:"march_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarchRemoveNotify) Reset() {
	*x = MarchRemoveNotify{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarchRemoveNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarchRemoveNotify) ProtoMessage() {}

func (x *MarchRemoveNotify) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarchRemoveNotify.ProtoReflect.Descriptor instead.
func (*MarchRemoveNotify) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{20}
}

func (x *MarchRemoveNotify) GetMarchId() int64 {
	if x != nil {
		return x.MarchId
	}
	return 0
}

type AllMarchSyncPush struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Marches       []*MarchInfo           `protobuf:"bytes,1,rep,name=marches,proto3" json:"marches,omitempty"`
	Rallies       []*RallyInfo           `protobuf:"bytes,2,rep,name=rallies,proto3" json:"rallies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllMarchSyncPush) Reset() {
	*x = AllMarchSyncPush{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllMarchSyncPush) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllMarchSyncPush) ProtoMessage() {}

func (x *AllMarchSyncPush) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllMarchSyncPush.ProtoReflect.Descriptor instead.
func (*AllMarchSyncPush) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{21}
}

func (x *AllMarchSyncPush) GetMarches() []*MarchInfo {
	if x != nil {
		return x.Marches
	}
	return nil
}

func (x *AllMarchSyncPush) GetRallies() []*RallyInfo {
	if x != nil {
		return x.Rallies
	}
	return nil
}

type BattleResultNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarchId       int64                  `protobuf:"varint,1,opt,name=march_id,json=marchId,proto3" json:"march_id,omitempty"`
	IsWin         bool                   `protobuf:"varint,2,opt,name=is_win,json=isWin,proto3" json:"is_win,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleResultNotify) Reset() {
	*x = BattleResultNotify{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleResultNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleResultNotify) ProtoMessage() {}

func (x *BattleResultNotify) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleResultNotify.ProtoReflect.Descriptor instead.
func (*BattleResultNotify) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{22}
}

func (x *BattleResultNotify) GetMarchId() int64 {
	if x != nil {
		return x.MarchId
	}
	return 0
}

func (x *BattleResultNotify) GetIsWin() bool {
	if x != nil {
		return x.IsWin
	}
	return false
}

type GatherResultNotify struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MarchId           int64                  `protobuf:"varint,1,opt,name=march_id,json=marchId,proto3" json:"march_id,omitempty"`
	GatheredResources map[int32]int64        `protobuf:"bytes,2,rep,name=gathered_resources,json=gatheredResources,proto3" json:"gathered_resources,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GatherResultNotify) Reset() {
	*x = GatherResultNotify{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatherResultNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatherResultNotify) ProtoMessage() {}

func (x *GatherResultNotify) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatherResultNotify.ProtoReflect.Descriptor instead.
func (*GatherResultNotify) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{23}
}

func (x *GatherResultNotify) GetMarchId() int64 {
	if x != nil {
		return x.MarchId
	}
	return 0
}

func (x *GatherResultNotify) GetGatheredResources() map[int32]int64 {
	if x != nil {
		return x.GatheredResources
	}
	return nil
}

type ScoutResultNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MarchId       int64                  `protobuf:"varint,1,opt,name=march_id,json=marchId,proto3" json:"march_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoutResultNotify) Reset() {
	*x = ScoutResultNotify{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoutResultNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoutResultNotify) ProtoMessage() {}

func (x *ScoutResultNotify) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoutResultNotify.ProtoReflect.Descriptor instead.
func (*ScoutResultNotify) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{24}
}

func (x *ScoutResultNotify) GetMarchId() int64 {
	if x != nil {
		return x.MarchId
	}
	return 0
}

type RallyCreateNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rally         *RallyInfo             `protobuf:"bytes,1,opt,name=rally,proto3" json:"rally,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RallyCreateNotify) Reset() {
	*x = RallyCreateNotify{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RallyCreateNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RallyCreateNotify) ProtoMessage() {}

func (x *RallyCreateNotify) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RallyCreateNotify.ProtoReflect.Descriptor instead.
func (*RallyCreateNotify) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{25}
}

func (x *RallyCreateNotify) GetRally() *RallyInfo {
	if x != nil {
		return x.Rally
	}
	return nil
}

type RallyUpdateNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rally         *RallyInfo             `protobuf:"bytes,1,opt,name=rally,proto3" json:"rally,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RallyUpdateNotify) Reset() {
	*x = RallyUpdateNotify{}
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RallyUpdateNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RallyUpdateNotify) ProtoMessage() {}

func (x *RallyUpdateNotify) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapmarch_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RallyUpdateNotify.ProtoReflect.Descriptor instead.
func (*RallyUpdateNotify) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapmarch_proto_rawDescGZIP(), []int{26}
}

func (x *RallyUpdateNotify) GetRally() *RallyInfo {
	if x != nil {
		return x.Rally
	}
	return nil
}

var File_mapsvr_bigmapmarch_proto protoreflect.FileDescriptor

const file_mapsvr_bigmapmarch_proto_rawDesc = "" +
	"\n" +
	"\x18mapsvr/bigmapmarch.proto\x12\x06mapsvr\x1a\x18common/types/types.proto\x1a\x13mapsvr/bigmap.proto\"\x96\x01\n" +
	"\vTroopLevels\x12G\n" +
	"\flevel_counts\x18\x01 \x03(\v2$.mapsvr.TroopLevels.LevelCountsEntryR\vlevelCounts\x1a>\n" +
	"\x10LevelCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xbc\x04\n" +
	"\tMarchInfo\x12\x19\n" +
	"\bmarch_id\x18\x01 \x01(\x03R\amarchId\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x120\n" +
	"\n" +
	"march_type\x18\x03 \x01(\x0e2\x11.mapsvr.MarchTypeR\tmarchType\x12(\n" +
	"\x05state\x18\x04 \x01(\x0e2\x12.mapsvr.MarchStateR\x05state\x12+\n" +
	"\bfrom_pos\x18\x05 \x01(\v2\x10.mapsvr.PositionR\afromPos\x12'\n" +
	"\x06to_pos\x18\x06 \x01(\v2\x10.mapsvr.PositionR\x05toPos\x12\x19\n" +
	"\bstart_at\x18\a \x01(\x03R\astartAt\x12\x1b\n" +
	"\tarrive_at\x18\b \x01(\x03R\barriveAt\x123\n" +
	"\vtarget_type\x18\t \x01(\x0e2\x12.mapsvr.TargetTypeR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\n" +
	" \x01(\x03R\btargetId\x12\x19\n" +
	"\bhero_ids\x18\v \x03(\x03R\aheroIds\x125\n" +
	"\x06troops\x18\f \x03(\v2\x1d.mapsvr.MarchInfo.TroopsEntryR\x06troops\x12\x19\n" +
	"\brally_id\x18\r \x01(\x03R\arallyId\x1aN\n" +
	"\vTroopsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.mapsvr.TroopLevelsR\x05value:\x028\x01\"\xd6\x01\n" +
	"\x0fRallyMemberInfo\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12;\n" +
	"\x06troops\x18\x02 \x03(\v2#.mapsvr.RallyMemberInfo.TroopsEntryR\x06troops\x12\x19\n" +
	"\bhero_ids\x18\x03 \x03(\x03R\aheroIds\x1aN\n" +
	"\vTroopsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.mapsvr.TroopLevelsR\x05value:\x028\x01\"\xa1\x03\n" +
	"\tRallyInfo\x12\x19\n" +
	"\brally_id\x18\x01 \x01(\x03R\arallyId\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\tR\bleaderId\x12\x1f\n" +
	"\valliance_id\x18\x03 \x01(\tR\n" +
	"allianceId\x12/\n" +
	"\n" +
	"target_pos\x18\x04 \x01(\v2\x10.mapsvr.PositionR\ttargetPos\x123\n" +
	"\vtarget_type\x18\x05 \x01(\x0e2\x12.mapsvr.TargetTypeR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x06 \x01(\x03R\btargetId\x12!\n" +
	"\fmax_capacity\x18\a \x01(\x03R\vmaxCapacity\x12\x1b\n" +
	"\tcreate_at\x18\b \x01(\x03R\bcreateAt\x12\x1b\n" +
	"\tlaunch_at\x18\t \x01(\x03R\blaunchAt\x12(\n" +
	"\x05state\x18\n" +
	" \x01(\x0e2\x12.mapsvr.RallyStateR\x05state\x121\n" +
	"\amembers\x18\v \x03(\v2\x17.mapsvr.RallyMemberInfoR\amembers\"\xea\x02\n" +
	"\x11StartMarchRequest\x120\n" +
	"\n" +
	"march_type\x18\x01 \x01(\x0e2\x11.mapsvr.MarchTypeR\tmarchType\x12'\n" +
	"\x06to_pos\x18\x02 \x01(\v2\x10.mapsvr.PositionR\x05toPos\x123\n" +
	"\vtarget_type\x18\x03 \x01(\x0e2\x12.mapsvr.TargetTypeR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x04 \x01(\x03R\btargetId\x12\x19\n" +
	"\bhero_ids\x18\x05 \x03(\x03R\aheroIds\x12=\n" +
	"\x06troops\x18\x06 \x03(\v2%.mapsvr.StartMarchRequest.TroopsEntryR\x06troops\x1aN\n" +
	"\vTroopsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.mapsvr.TroopLevelsR\x05value:\x028\x01\"d\n" +
	"\x12StartMarchResponse\x12%\n" +
	"\x04resp\x18\x01 \x01(\v2\x11.types.CommonRespR\x04resp\x12'\n" +
	"\x05march\x18\x02 \x01(\v2\x11.mapsvr.MarchInfoR\x05march\"/\n" +
	"\x12CancelMarchRequest\x12\x19\n" +
	"\bmarch_id\x18\x01 \x01(\x03R\amarchId\"<\n" +
	"\x13CancelMarchResponse\x12%\n" +
	"\x04resp\x18\x01 \x01(\v2\x11.types.CommonRespR\x04resp\"d\n" +
	"\x13SpeedUpMarchRequest\x12\x19\n" +
	"\bmarch_id\x18\x01 \x01(\x03R\amarchId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x05R\x06itemId\x12\x19\n" +
	"\bitem_num\x18\x03 \x01(\x05R\aitemNum\"a\n" +
	"\x14SpeedUpMarchResponse\x12%\n" +
	"\x04resp\x18\x01 \x01(\v2\x11.types.CommonRespR\x04resp\x12\"\n" +
	"\rnew_arrive_at\x18\x02 \x01(\x03R\vnewArriveAt\"\xe7\x02\n" +
	"\x12CreateRallyRequest\x12/\n" +
	"\n" +
	"target_pos\x18\x01 \x01(\v2\x10.mapsvr.PositionR\ttargetPos\x123\n" +
	"\vtarget_type\x18\x02 \x01(\x0e2\x12.mapsvr.TargetTypeR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x03 \x01(\x03R\btargetId\x12#\n" +
	"\rwait_duration\x18\x04 \x01(\x03R\fwaitDuration\x12\x19\n" +
	"\bhero_ids\x18\x05 \x03(\x03R\aheroIds\x12>\n" +
	"\x06troops\x18\x06 \x03(\v2&.mapsvr.CreateRallyRequest.TroopsEntryR\x06troops\x1aN\n" +
	"\vTroopsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.mapsvr.TroopLevelsR\x05value:\x028\x01\"e\n" +
	"\x13CreateRallyResponse\x12%\n" +
	"\x04resp\x18\x01 \x01(\v2\x11.types.CommonRespR\x04resp\x12'\n" +
	"\x05rally\x18\x02 \x01(\v2\x11.mapsvr.RallyInfoR\x05rally\"\xd6\x01\n" +
	"\x10JoinRallyRequest\x12\x19\n" +
	"\brally_id\x18\x01 \x01(\x03R\arallyId\x12\x19\n" +
	"\bhero_ids\x18\x02 \x03(\x03R\aheroIds\x12<\n" +
	"\x06troops\x18\x03 \x03(\v2$.mapsvr.JoinRallyRequest.TroopsEntryR\x06troops\x1aN\n" +
	"\vTroopsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.mapsvr.TroopLevelsR\x05value:\x028\x01\":\n" +
	"\x11JoinRallyResponse\x12%\n" +
	"\x04resp\x18\x01 \x01(\v2\x11.types.CommonRespR\x04resp\"/\n" +
	"\x12LaunchRallyRequest\x12\x19\n" +
	"\brally_id\x18\x01 \x01(\x03R\arallyId\"<\n" +
	"\x13LaunchRallyResponse\x12%\n" +
	"\x04resp\x18\x01 \x01(\v2\x11.types.CommonRespR\x04resp\"/\n" +
	"\x12CancelRallyRequest\x12\x19\n" +
	"\brally_id\x18\x01 \x01(\x03R\arallyId\"<\n" +
	"\x13CancelRallyResponse\x12%\n" +
	"\x04resp\x18\x01 \x01(\v2\x11.types.CommonRespR\x04resp\"<\n" +
	"\x11MarchCreateNotify\x12'\n" +
	"\x05march\x18\x01 \x01(\v2\x11.mapsvr.MarchInfoR\x05march\";\n" +
	"\x10MarchStateNotify\x12'\n" +
	"\x05march\x18\x01 \x01(\v2\x11.mapsvr.MarchInfoR\x05march\".\n" +
	"\x11MarchRemoveNotify\x12\x19\n" +
	"\bmarch_id\x18\x01 \x01(\x03R\amarchId\"l\n" +
	"\x10AllMarchSyncPush\x12+\n" +
	"\amarches\x18\x01 \x03(\v2\x11.mapsvr.MarchInfoR\amarches\x12+\n" +
	"\arallies\x18\x02 \x03(\v2\x11.mapsvr.RallyInfoR\arallies\"F\n" +
	"\x12BattleResultNotify\x12\x19\n" +
	"\bmarch_id\x18\x01 \x01(\x03R\amarchId\x12\x15\n" +
	"\x06is_win\x18\x02 \x01(\bR\x05isWin\"\xd7\x01\n" +
	"\x12GatherResultNotify\x12\x19\n" +
	"\bmarch_id\x18\x01 \x01(\x03R\amarchId\x12`\n" +
	"\x12gathered_resources\x18\x02 \x03(\v21.mapsvr.GatherResultNotify.GatheredResourcesEntryR\x11gatheredResources\x1aD\n" +
	"\x16GatheredResourcesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\".\n" +
	"\x11ScoutResultNotify\x12\x19\n" +
	"\bmarch_id\x18\x01 \x01(\x03R\amarchId\"<\n" +
	"\x11RallyCreateNotify\x12'\n" +
	"\x05rally\x18\x01 \x01(\v2\x11.mapsvr.RallyInfoR\x05rally\"<\n" +
	"\x11RallyUpdateNotify\x12'\n" +
	"\x05rally\x18\x01 \x01(\v2\x11.mapsvr.RallyInfoR\x05rally*N\n" +
	"\tTroopType\x12\x1a\n" +
	"\x16TROOP_TYPE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bINFANTRY\x10\x01\x12\v\n" +
	"\aCAVALRY\x10\x02\x12\n" +
	"\n" +
	"\x06ARCHER\x10\x03*\xcd\x01\n" +
	"\tMarchType\x12\x1a\n" +
	"\x16MARCH_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11MARCH_TYPE_ATTACK\x10\x01\x12\x15\n" +
	"\x11MARCH_TYPE_GATHER\x10\x02\x12\x14\n" +
	"\x10MARCH_TYPE_SCOUT\x10\x03\x12\x14\n" +
	"\x10MARCH_TYPE_RALLY\x10\x04\x12\x18\n" +
	"\x14MARCH_TYPE_REINFORCE\x10\x05\x12\x15\n" +
	"\x11MARCH_TYPE_RETURN\x10\x06\x12\x19\n" +
	"\x15MARCH_TYPE_RALLY_LEAD\x10\a*\xc8\x01\n" +
	"\n" +
	"MarchState\x12\x1b\n" +
	"\x17MARCH_STATE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14MARCH_STATE_MARCHING\x10\x01\x12\x18\n" +
	"\x14MARCH_STATE_FIGHTING\x10\x02\x12\x19\n" +
	"\x15MARCH_STATE_GATHERING\x10\x03\x12\x19\n" +
	"\x15MARCH_STATE_STATIONED\x10\x04\x12\x18\n" +
	"\x14MARCH_STATE_SCOUTING\x10\x05\x12\x19\n" +
	"\x15MARCH_STATE_RETURNING\x10\x06*\x93\x01\n" +
	"\n" +
	"TargetType\x12\x1b\n" +
	"\x17TARGET_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17TARGET_TYPE_PLAYER_CITY\x10\x01\x12\x17\n" +
	"\x13TARGET_TYPE_MONSTER\x10\x02\x12\x18\n" +
	"\x14TARGET_TYPE_RESOURCE\x10\x03\x12\x18\n" +
	"\x14TARGET_TYPE_ALLIANCE\x10\x04*\x8d\x01\n" +
	"\n" +
	"RallyState\x12\x1b\n" +
	"\x17RALLY_STATE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13RALLY_STATE_WAITING\x10\x01\x12\x18\n" +
	"\x14RALLY_STATE_MARCHING\x10\x02\x12\x18\n" +
	"\x14RALLY_STATE_FIGHTING\x10\x03\x12\x15\n" +
	"\x11RALLY_STATE_ENDED\x10\x04B.Z,pitaya-game/protos/protobuf/pb/golang/mapsvrb\x06proto3"

var (
	file_mapsvr_bigmapmarch_proto_rawDescOnce sync.Once
	file_mapsvr_bigmapmarch_proto_rawDescData []byte
)

func file_mapsvr_bigmapmarch_proto_rawDescGZIP() []byte {
	file_mapsvr_bigmapmarch_proto_rawDescOnce.Do(func() {
		file_mapsvr_bigmapmarch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mapsvr_bigmapmarch_proto_rawDesc), len(file_mapsvr_bigmapmarch_proto_rawDesc)))
	})
	return file_mapsvr_bigmapmarch_proto_rawDescData
}

var file_mapsvr_bigmapmarch_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_mapsvr_bigmapmarch_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_mapsvr_bigmapmarch_proto_goTypes = []any{
	(TroopType)(0),               // 0: mapsvr.TroopType
	(MarchType)(0),               // 1: mapsvr.MarchType
	(MarchState)(0),              // 2: mapsvr.MarchState
	(TargetType)(0),              // 3: mapsvr.TargetType
	(RallyState)(0),              // 4: mapsvr.RallyState
	(*TroopLevels)(nil),          // 5: mapsvr.TroopLevels
	(*MarchInfo)(nil),            // 6: mapsvr.MarchInfo
	(*RallyMemberInfo)(nil),      // 7: mapsvr.RallyMemberInfo
	(*RallyInfo)(nil),            // 8: mapsvr.RallyInfo
	(*StartMarchRequest)(nil),    // 9: mapsvr.StartMarchRequest
	(*StartMarchResponse)(nil),   // 10: mapsvr.StartMarchResponse
	(*CancelMarchRequest)(nil),   // 11: mapsvr.CancelMarchRequest
	(*CancelMarchResponse)(nil),  // 12: mapsvr.CancelMarchResponse
	(*SpeedUpMarchRequest)(nil),  // 13: mapsvr.SpeedUpMarchRequest
	(*SpeedUpMarchResponse)(nil), // 14: mapsvr.SpeedUpMarchResponse
	(*CreateRallyRequest)(nil),   // 15: mapsvr.CreateRallyRequest
	(*CreateRallyResponse)(nil),  // 16: mapsvr.CreateRallyResponse
	(*JoinRallyRequest)(nil),     // 17: mapsvr.JoinRallyRequest
	(*JoinRallyResponse)(nil),    // 18: mapsvr.JoinRallyResponse
	(*LaunchRallyRequest)(nil),   // 19: mapsvr.LaunchRallyRequest
	(*LaunchRallyResponse)(nil),  // 20: mapsvr.LaunchRallyResponse
	(*CancelRallyRequest)(nil),   // 21: mapsvr.CancelRallyRequest
	(*CancelRallyResponse)(nil),  // 22: mapsvr.CancelRallyResponse
	(*MarchCreateNotify)(nil),    // 23: mapsvr.MarchCreateNotify
	(*MarchStateNotify)(nil),     // 24: mapsvr.MarchStateNotify
	(*MarchRemoveNotify)(nil),    // 25: mapsvr.MarchRemoveNotify
	(*AllMarchSyncPush)(nil),     // 26: mapsvr.AllMarchSyncPush
	(*BattleResultNotify)(nil),   // 27: mapsvr.BattleResultNotify
	(*GatherResultNotify)(nil),   // 28: mapsvr.GatherResultNotify
	(*ScoutResultNotify)(nil),    // 29: mapsvr.ScoutResultNotify
	(*RallyCreateNotify)(nil),    // 30: mapsvr.RallyCreateNotify
	(*RallyUpdateNotify)(nil),    // 31: mapsvr.RallyUpdateNotify
	nil,                          // 32: mapsvr.TroopLevels.LevelCountsEntry
	nil,                          // 33: mapsvr.MarchInfo.TroopsEntry
	nil,                          // 34: mapsvr.RallyMemberInfo.TroopsEntry
	nil,                          // 35: mapsvr.StartMarchRequest.TroopsEntry
	nil,                          // 36: mapsvr.CreateRallyRequest.TroopsEntry
	nil,                          // 37: mapsvr.JoinRallyRequest.TroopsEntry
	nil,                          // 38: mapsvr.GatherResultNotify.GatheredResourcesEntry
	(*Position)(nil),             // 39: mapsvr.Position
	(*types.CommonResp)(nil),     // 40: types.CommonResp
}
var file_mapsvr_bigmapmarch_proto_depIdxs = []int32{
	32, // 0: mapsvr.TroopLevels.level_counts:type_name -> mapsvr.TroopLevels.LevelCountsEntry
	1,  // 1: mapsvr.MarchInfo.march_type:type_name -> mapsvr.MarchType
	2,  // 2: mapsvr.MarchInfo.state:type_name -> mapsvr.MarchState
	39, // 3: mapsvr.MarchInfo.from_pos:type_name -> mapsvr.Position
	39, // 4: mapsvr.MarchInfo.to_pos:type_name -> mapsvr.Position
	3,  // 5: mapsvr.MarchInfo.target_type:type_name -> mapsvr.TargetType
	33, // 6: mapsvr.MarchInfo.troops:type_name -> mapsvr.MarchInfo.TroopsEntry
	34, // 7: mapsvr.RallyMemberInfo.troops:type_name -> mapsvr.RallyMemberInfo.TroopsEntry
	39, // 8: mapsvr.RallyInfo.target_pos:type_name -> mapsvr.Position
	3,  // 9: mapsvr.RallyInfo.target_type:type_name -> mapsvr.TargetType
	4,  // 10: mapsvr.RallyInfo.state:type_name -> mapsvr.RallyState
	7,  // 11: mapsvr.RallyInfo.members:type_name -> mapsvr.RallyMemberInfo
	1,  // 12: mapsvr.StartMarchRequest.march_type:type_name -> mapsvr.MarchType
	39, // 13: mapsvr.StartMarchRequest.to_pos:type_name -> mapsvr.Position
	3,  // 14: mapsvr.StartMarchRequest.target_type:type_name -> mapsvr.TargetType
	35, // 15: mapsvr.StartMarchRequest.troops:type_name -> mapsvr.StartMarchRequest.TroopsEntry
	40, // 16: mapsvr.StartMarchResponse.resp:type_name -> types.CommonResp
	6,  // 17: mapsvr.StartMarchResponse.march:type_name -> mapsvr.MarchInfo
	40, // 18: mapsvr.CancelMarchResponse.resp:type_name -> types.CommonResp
	40, // 19: mapsvr.SpeedUpMarchResponse.resp:type_name -> types.CommonResp
	39, // 20: mapsvr.CreateRallyRequest.target_pos:type_name -> mapsvr.Position
	3,  // 21: mapsvr.CreateRallyRequest.target_type:type_name -> mapsvr.TargetType
	36, // 22: mapsvr.CreateRallyRequest.troops:type_name -> mapsvr.CreateRallyRequest.TroopsEntry
	40, // 23: mapsvr.CreateRallyResponse.resp:type_name -> types.CommonResp
	8,  // 24: mapsvr.CreateRallyResponse.rally:type_name -> mapsvr.RallyInfo
	37, // 25: mapsvr.JoinRallyRequest.troops:type_name -> mapsvr.JoinRallyRequest.TroopsEntry
	40, // 26: mapsvr.JoinRallyResponse.resp:type_name -> types.CommonResp
	40, // 27: mapsvr.LaunchRallyResponse.resp:type_name -> types.CommonResp
	40, // 28: mapsvr.CancelRallyResponse.resp:type_name -> types.CommonResp
	6,  // 29: mapsvr.MarchCreateNotify.march:type_name -> mapsvr.MarchInfo
	6,  // 30: mapsvr.MarchStateNotify.march:type_name -> mapsvr.MarchInfo
	6,  // 31: mapsvr.AllMarchSyncPush.marches:type_name -> mapsvr.MarchInfo
	8,  // 32: mapsvr.AllMarchSyncPush.rallies:type_name -> mapsvr.RallyInfo
	38, // 33: mapsvr.GatherResultNotify.gathered_resources:type_name -> mapsvr.GatherResultNotify.GatheredResourcesEntry
	8,  // 34: mapsvr.RallyCreateNotify.rally:type_name -> mapsvr.RallyInfo
	8,  // 35: mapsvr.RallyUpdateNotify.rally:type_name -> mapsvr.RallyInfo
	5,  // 36: mapsvr.MarchInfo.TroopsEntry.value:type_name -> mapsvr.TroopLevels
	5,  // 37: mapsvr.RallyMemberInfo.TroopsEntry.value:type_name -> mapsvr.TroopLevels
	5,  // 38: mapsvr.StartMarchRequest.TroopsEntry.value:type_name -> mapsvr.TroopLevels
	5,  // 39: mapsvr.CreateRallyRequest.TroopsEntry.value:type_name -> mapsvr.TroopLevels
	5,  // 40: mapsvr.JoinRallyRequest.TroopsEntry.value:type_name -> mapsvr.TroopLevels
	41, // [41:41] is the sub-list for method output_type
	41, // [41:41] is the sub-list for method input_type
	41, // [41:41] is the sub-list for extension type_name
	41, // [41:41] is the sub-list for extension extendee
	0,  // [0:41] is the sub-list for field type_name
}

func init() { file_mapsvr_bigmapmarch_proto_init() }
func file_mapsvr_bigmapmarch_proto_init() {
	if File_mapsvr_bigmapmarch_proto != nil {
		return
	}
	file_mapsvr_bigmap_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mapsvr_bigmapmarch_proto_rawDesc), len(file_mapsvr_bigmapmarch_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mapsvr_bigmapmarch_proto_goTypes,
		DependencyIndexes: file_mapsvr_bigmapmarch_proto_depIdxs,
		EnumInfos:         file_mapsvr_bigmapmarch_proto_enumTypes,
		MessageInfos:      file_mapsvr_bigmapmarch_proto_msgTypes,
	}.Build()
	File_mapsvr_bigmapmarch_proto = out.File
	file_mapsvr_bigmapmarch_proto_goTypes = nil
	file_mapsvr_bigmapmarch_proto_depIdxs = nil
}
