// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: mapsvr/bigmapbattle.proto

package mapsvr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	types "pitaya-game/protos/protobuf/pb/golang/common/types"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BattleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleRequest) Reset() {
	*x = BattleRequest{}
	mi := &file_mapsvr_bigmapbattle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleRequest) ProtoMessage() {}

func (x *BattleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapbattle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleRequest.ProtoReflect.Descriptor instead.
func (*BattleRequest) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapbattle_proto_rawDescGZIP(), []int{0}
}

type FighterInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PlayerId          string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	X                 int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`
	Y                 int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`
	SoldierCount      int32                  `protobuf:"varint,4,opt,name=soldier_count,json=soldierCount,proto3" json:"soldier_count,omitempty"`
	DeathCount        int32                  `protobuf:"varint,5,opt,name=death_count,json=deathCount,proto3" json:"death_count,omitempty"`
	LiveCount         int32                  `protobuf:"varint,6,opt,name=live_count,json=liveCount,proto3" json:"live_count,omitempty"`
	TroopKillCountMap map[int32]int32        `protobuf:"bytes,7,rep,name=troop_kill_count_map,json=troopKillCountMap,proto3" json:"troop_kill_count_map,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FighterInfo) Reset() {
	*x = FighterInfo{}
	mi := &file_mapsvr_bigmapbattle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FighterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FighterInfo) ProtoMessage() {}

func (x *FighterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapbattle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FighterInfo.ProtoReflect.Descriptor instead.
func (*FighterInfo) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapbattle_proto_rawDescGZIP(), []int{1}
}

func (x *FighterInfo) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *FighterInfo) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *FighterInfo) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *FighterInfo) GetSoldierCount() int32 {
	if x != nil {
		return x.SoldierCount
	}
	return 0
}

func (x *FighterInfo) GetDeathCount() int32 {
	if x != nil {
		return x.DeathCount
	}
	return 0
}

func (x *FighterInfo) GetLiveCount() int32 {
	if x != nil {
		return x.LiveCount
	}
	return 0
}

func (x *FighterInfo) GetTroopKillCountMap() map[int32]int32 {
	if x != nil {
		return x.TroopKillCountMap
	}
	return nil
}

type BattleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *types.CommonResp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	Attacker      *FighterInfo           `protobuf:"bytes,2,opt,name=attacker,proto3" json:"attacker,omitempty"`
	Defencer      *FighterInfo           `protobuf:"bytes,3,opt,name=defencer,proto3" json:"defencer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleResponse) Reset() {
	*x = BattleResponse{}
	mi := &file_mapsvr_bigmapbattle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleResponse) ProtoMessage() {}

func (x *BattleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapbattle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleResponse.ProtoReflect.Descriptor instead.
func (*BattleResponse) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapbattle_proto_rawDescGZIP(), []int{2}
}

func (x *BattleResponse) GetResp() *types.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *BattleResponse) GetAttacker() *FighterInfo {
	if x != nil {
		return x.Attacker
	}
	return nil
}

func (x *BattleResponse) GetDefencer() *FighterInfo {
	if x != nil {
		return x.Defencer
	}
	return nil
}

var File_mapsvr_bigmapbattle_proto protoreflect.FileDescriptor

const file_mapsvr_bigmapbattle_proto_rawDesc = "" +
	"\n" +
	"\x19mapsvr/bigmapbattle.proto\x12\x06mapsvr\x1a\x18common/types/types.proto\"\x0f\n" +
	"\rBattleRequest\"\xce\x02\n" +
	"\vFighterInfo\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\x12#\n" +
	"\rsoldier_count\x18\x04 \x01(\x05R\fsoldierCount\x12\x1f\n" +
	"\vdeath_count\x18\x05 \x01(\x05R\n" +
	"deathCount\x12\x1d\n" +
	"\n" +
	"live_count\x18\x06 \x01(\x05R\tliveCount\x12[\n" +
	"\x14troop_kill_count_map\x18\a \x03(\v2*.mapsvr.FighterInfo.TroopKillCountMapEntryR\x11troopKillCountMap\x1aD\n" +
	"\x16TroopKillCountMapEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x99\x01\n" +
	"\x0eBattleResponse\x12%\n" +
	"\x04resp\x18\x01 \x01(\v2\x11.types.CommonRespR\x04resp\x12/\n" +
	"\battacker\x18\x02 \x01(\v2\x13.mapsvr.FighterInfoR\battacker\x12/\n" +
	"\bdefencer\x18\x03 \x01(\v2\x13.mapsvr.FighterInfoR\bdefencerB.Z,pitaya-game/protos/protobuf/pb/golang/mapsvrb\x06proto3"

var (
	file_mapsvr_bigmapbattle_proto_rawDescOnce sync.Once
	file_mapsvr_bigmapbattle_proto_rawDescData []byte
)

func file_mapsvr_bigmapbattle_proto_rawDescGZIP() []byte {
	file_mapsvr_bigmapbattle_proto_rawDescOnce.Do(func() {
		file_mapsvr_bigmapbattle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mapsvr_bigmapbattle_proto_rawDesc), len(file_mapsvr_bigmapbattle_proto_rawDesc)))
	})
	return file_mapsvr_bigmapbattle_proto_rawDescData
}

var file_mapsvr_bigmapbattle_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_mapsvr_bigmapbattle_proto_goTypes = []any{
	(*BattleRequest)(nil),    // 0: mapsvr.BattleRequest
	(*FighterInfo)(nil),      // 1: mapsvr.FighterInfo
	(*BattleResponse)(nil),   // 2: mapsvr.BattleResponse
	nil,                      // 3: mapsvr.FighterInfo.TroopKillCountMapEntry
	(*types.CommonResp)(nil), // 4: types.CommonResp
}
var file_mapsvr_bigmapbattle_proto_depIdxs = []int32{
	3, // 0: mapsvr.FighterInfo.troop_kill_count_map:type_name -> mapsvr.FighterInfo.TroopKillCountMapEntry
	4, // 1: mapsvr.BattleResponse.resp:type_name -> types.CommonResp
	1, // 2: mapsvr.BattleResponse.attacker:type_name -> mapsvr.FighterInfo
	1, // 3: mapsvr.BattleResponse.defencer:type_name -> mapsvr.FighterInfo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_mapsvr_bigmapbattle_proto_init() }
func file_mapsvr_bigmapbattle_proto_init() {
	if File_mapsvr_bigmapbattle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mapsvr_bigmapbattle_proto_rawDesc), len(file_mapsvr_bigmapbattle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mapsvr_bigmapbattle_proto_goTypes,
		DependencyIndexes: file_mapsvr_bigmapbattle_proto_depIdxs,
		MessageInfos:      file_mapsvr_bigmapbattle_proto_msgTypes,
	}.Build()
	File_mapsvr_bigmapbattle_proto = out.File
	file_mapsvr_bigmapbattle_proto_goTypes = nil
	file_mapsvr_bigmapbattle_proto_depIdxs = nil
}
