// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: mapsvr/bigmap.proto

package mapsvr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	_ "pitaya-game/protos/protobuf/pb/golang/common/errors"
	types "pitaya-game/protos/protobuf/pb/golang/common/types"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_mapsvr_bigmap_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmap_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmap_proto_rawDescGZIP(), []int{0}
}

func (x *Position) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Position) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Size struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	W             int32                  `protobuf:"varint,1,opt,name=w,proto3" json:"w,omitempty"`
	H             int32                  `protobuf:"varint,2,opt,name=h,proto3" json:"h,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Size) Reset() {
	*x = Size{}
	mi := &file_mapsvr_bigmap_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Size) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Size) ProtoMessage() {}

func (x *Size) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmap_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Size.ProtoReflect.Descriptor instead.
func (*Size) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmap_proto_rawDescGZIP(), []int{1}
}

func (x *Size) GetW() int32 {
	if x != nil {
		return x.W
	}
	return 0
}

func (x *Size) GetH() int32 {
	if x != nil {
		return x.H
	}
	return 0
}

type EnterMapRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Layer int32                  `protobuf:"varint,1,opt,name=layer,proto3" json:"layer,omitempty"`
	// 视野中心点格子的左下角坐标
	Position *Position `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	// 1.5屏幕格子数
	Size          *Size `protobuf:"bytes,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterMapRequest) Reset() {
	*x = EnterMapRequest{}
	mi := &file_mapsvr_bigmap_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterMapRequest) ProtoMessage() {}

func (x *EnterMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmap_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterMapRequest.ProtoReflect.Descriptor instead.
func (*EnterMapRequest) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmap_proto_rawDescGZIP(), []int{2}
}

func (x *EnterMapRequest) GetLayer() int32 {
	if x != nil {
		return x.Layer
	}
	return 0
}

func (x *EnterMapRequest) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *EnterMapRequest) GetSize() *Size {
	if x != nil {
		return x.Size
	}
	return nil
}

type EnterMapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *types.CommonResp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnterMapResponse) Reset() {
	*x = EnterMapResponse{}
	mi := &file_mapsvr_bigmap_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnterMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnterMapResponse) ProtoMessage() {}

func (x *EnterMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmap_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnterMapResponse.ProtoReflect.Descriptor instead.
func (*EnterMapResponse) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmap_proto_rawDescGZIP(), []int{3}
}

func (x *EnterMapResponse) GetResp() *types.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

type MoveViewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Layer         int32                  `protobuf:"varint,1,opt,name=layer,proto3" json:"layer,omitempty"`
	Center        *Position              `protobuf:"bytes,2,opt,name=center,proto3" json:"center,omitempty"`
	Size          *Size                  `protobuf:"bytes,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveViewRequest) Reset() {
	*x = MoveViewRequest{}
	mi := &file_mapsvr_bigmap_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveViewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveViewRequest) ProtoMessage() {}

func (x *MoveViewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmap_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveViewRequest.ProtoReflect.Descriptor instead.
func (*MoveViewRequest) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmap_proto_rawDescGZIP(), []int{4}
}

func (x *MoveViewRequest) GetLayer() int32 {
	if x != nil {
		return x.Layer
	}
	return 0
}

func (x *MoveViewRequest) GetCenter() *Position {
	if x != nil {
		return x.Center
	}
	return nil
}

func (x *MoveViewRequest) GetSize() *Size {
	if x != nil {
		return x.Size
	}
	return nil
}

type MoveViewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *types.CommonResp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveViewResponse) Reset() {
	*x = MoveViewResponse{}
	mi := &file_mapsvr_bigmap_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveViewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveViewResponse) ProtoMessage() {}

func (x *MoveViewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmap_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveViewResponse.ProtoReflect.Descriptor instead.
func (*MoveViewResponse) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmap_proto_rawDescGZIP(), []int{5}
}

func (x *MoveViewResponse) GetResp() *types.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

type LeaveMapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveMapRequest) Reset() {
	*x = LeaveMapRequest{}
	mi := &file_mapsvr_bigmap_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveMapRequest) ProtoMessage() {}

func (x *LeaveMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmap_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveMapRequest.ProtoReflect.Descriptor instead.
func (*LeaveMapRequest) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmap_proto_rawDescGZIP(), []int{6}
}

type LeaveMapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *types.CommonResp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveMapResponse) Reset() {
	*x = LeaveMapResponse{}
	mi := &file_mapsvr_bigmap_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveMapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveMapResponse) ProtoMessage() {}

func (x *LeaveMapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmap_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveMapResponse.ProtoReflect.Descriptor instead.
func (*LeaveMapResponse) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmap_proto_rawDescGZIP(), []int{7}
}

func (x *LeaveMapResponse) GetResp() *types.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

// ------------------- Entity ------------------
type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ConfigId      int32                  `protobuf:"varint,2,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	Type          int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	SubType       int32                  `protobuf:"varint,4,opt,name=sub_type,json=subType,proto3" json:"sub_type,omitempty"`
	Data          []*anypb.Any           `protobuf:"bytes,5,rep,name=data,proto3" json:"data,omitempty"`
	Pos           *Position              `protobuf:"bytes,6,opt,name=pos,proto3" json:"pos,omitempty"`
	Version       int64                  `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	GridId        int32                  `protobuf:"varint,8,opt,name=gridId,proto3" json:"gridId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_mapsvr_bigmap_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmap_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmap_proto_rawDescGZIP(), []int{8}
}

func (x *Entity) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Entity) GetConfigId() int32 {
	if x != nil {
		return x.ConfigId
	}
	return 0
}

func (x *Entity) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Entity) GetSubType() int32 {
	if x != nil {
		return x.SubType
	}
	return 0
}

func (x *Entity) GetData() []*anypb.Any {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Entity) GetPos() *Position {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *Entity) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Entity) GetGridId() int32 {
	if x != nil {
		return x.GridId
	}
	return 0
}

type EntityStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAlive       bool                   `protobuf:"varint,1,opt,name=IsAlive,proto3" json:"IsAlive,omitempty"`
	IsLowHealth   bool                   `protobuf:"varint,2,opt,name=IsLowHealth,proto3" json:"IsLowHealth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntityStatus) Reset() {
	*x = EntityStatus{}
	mi := &file_mapsvr_bigmap_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntityStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityStatus) ProtoMessage() {}

func (x *EntityStatus) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmap_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityStatus.ProtoReflect.Descriptor instead.
func (*EntityStatus) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmap_proto_rawDescGZIP(), []int{9}
}

func (x *EntityStatus) GetIsAlive() bool {
	if x != nil {
		return x.IsAlive
	}
	return false
}

func (x *EntityStatus) GetIsLowHealth() bool {
	if x != nil {
		return x.IsLowHealth
	}
	return false
}

type BornTime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BornTime) Reset() {
	*x = BornTime{}
	mi := &file_mapsvr_bigmap_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BornTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BornTime) ProtoMessage() {}

func (x *BornTime) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmap_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BornTime.ProtoReflect.Descriptor instead.
func (*BornTime) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmap_proto_rawDescGZIP(), []int{10}
}

func (x *BornTime) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type LowHealthTime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LowHealthTime) Reset() {
	*x = LowHealthTime{}
	mi := &file_mapsvr_bigmap_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LowHealthTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LowHealthTime) ProtoMessage() {}

func (x *LowHealthTime) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmap_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LowHealthTime.ProtoReflect.Descriptor instead.
func (*LowHealthTime) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmap_proto_rawDescGZIP(), []int{11}
}

func (x *LowHealthTime) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type DeadTime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeadTime) Reset() {
	*x = DeadTime{}
	mi := &file_mapsvr_bigmap_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeadTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeadTime) ProtoMessage() {}

func (x *DeadTime) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmap_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeadTime.ProtoReflect.Descriptor instead.
func (*DeadTime) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmap_proto_rawDescGZIP(), []int{12}
}

func (x *DeadTime) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

type Grid struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Pos           *Position              `protobuf:"bytes,2,opt,name=pos,proto3" json:"pos,omitempty"`
	Version       int64                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	EntityId      int32                  `protobuf:"varint,6,opt,name=entityId,proto3" json:"entityId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Grid) Reset() {
	*x = Grid{}
	mi := &file_mapsvr_bigmap_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Grid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Grid) ProtoMessage() {}

func (x *Grid) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmap_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Grid.ProtoReflect.Descriptor instead.
func (*Grid) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmap_proto_rawDescGZIP(), []int{13}
}

func (x *Grid) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Grid) GetPos() *Position {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *Grid) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Grid) GetEntityId() int32 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

type AOIUpdateNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Entities      []*Entity              `protobuf:"bytes,3,rep,name=entities,proto3" json:"entities,omitempty"`                               // 全量或增量实体列表
	RemovedIds    []int32                `protobuf:"varint,4,rep,packed,name=removed_ids,json=removedIds,proto3" json:"removed_ids,omitempty"` // 增量中的实体移除ID列表
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AOIUpdateNotify) Reset() {
	*x = AOIUpdateNotify{}
	mi := &file_mapsvr_bigmap_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AOIUpdateNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AOIUpdateNotify) ProtoMessage() {}

func (x *AOIUpdateNotify) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmap_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AOIUpdateNotify.ProtoReflect.Descriptor instead.
func (*AOIUpdateNotify) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmap_proto_rawDescGZIP(), []int{14}
}

func (x *AOIUpdateNotify) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *AOIUpdateNotify) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *AOIUpdateNotify) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *AOIUpdateNotify) GetRemovedIds() []int32 {
	if x != nil {
		return x.RemovedIds
	}
	return nil
}

func (x *AOIUpdateNotify) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_mapsvr_bigmap_proto protoreflect.FileDescriptor

const file_mapsvr_bigmap_proto_rawDesc = "" +
	"\n" +
	"\x13mapsvr/bigmap.proto\x12\x06mapsvr\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18common/types/types.proto\x1a\x1acommon/errors/errors.proto\"&\n" +
	"\bPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"\"\n" +
	"\x04Size\x12\f\n" +
	"\x01w\x18\x01 \x01(\x05R\x01w\x12\f\n" +
	"\x01h\x18\x02 \x01(\x05R\x01h\"w\n" +
	"\x0fEnterMapRequest\x12\x14\n" +
	"\x05layer\x18\x01 \x01(\x05R\x05layer\x12,\n" +
	"\bposition\x18\x02 \x01(\v2\x10.mapsvr.PositionR\bposition\x12 \n" +
	"\x04size\x18\x03 \x01(\v2\f.mapsvr.SizeR\x04size\"9\n" +
	"\x10EnterMapResponse\x12%\n" +
	"\x04resp\x18\x01 \x01(\v2\x11.types.CommonRespR\x04resp\"s\n" +
	"\x0fMoveViewRequest\x12\x14\n" +
	"\x05layer\x18\x01 \x01(\x05R\x05layer\x12(\n" +
	"\x06center\x18\x02 \x01(\v2\x10.mapsvr.PositionR\x06center\x12 \n" +
	"\x04size\x18\x03 \x01(\v2\f.mapsvr.SizeR\x04size\"9\n" +
	"\x10MoveViewResponse\x12%\n" +
	"\x04resp\x18\x01 \x01(\v2\x11.types.CommonRespR\x04resp\"\x11\n" +
	"\x0fLeaveMapRequest\"9\n" +
	"\x10LeaveMapResponse\x12%\n" +
	"\x04resp\x18\x01 \x01(\v2\x11.types.CommonRespR\x04resp\"\xe4\x01\n" +
	"\x06Entity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\tconfig_id\x18\x02 \x01(\x05R\bconfigId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\x12\x19\n" +
	"\bsub_type\x18\x04 \x01(\x05R\asubType\x12(\n" +
	"\x04data\x18\x05 \x03(\v2\x14.google.protobuf.AnyR\x04data\x12\"\n" +
	"\x03pos\x18\x06 \x01(\v2\x10.mapsvr.PositionR\x03pos\x12\x18\n" +
	"\aversion\x18\a \x01(\x03R\aversion\x12\x16\n" +
	"\x06gridId\x18\b \x01(\x05R\x06gridId\"J\n" +
	"\fEntityStatus\x12\x18\n" +
	"\aIsAlive\x18\x01 \x01(\bR\aIsAlive\x12 \n" +
	"\vIsLowHealth\x18\x02 \x01(\bR\vIsLowHealth\":\n" +
	"\bBornTime\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\"?\n" +
	"\rLowHealthTime\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\":\n" +
	"\bDeadTime\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\"p\n" +
	"\x04Grid\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\"\n" +
	"\x03pos\x18\x02 \x01(\v2\x10.mapsvr.PositionR\x03pos\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x03R\aversion\x12\x1a\n" +
	"\bentityId\x18\x06 \x01(\x05R\bentityId\"\x98\x01\n" +
	"\x0fAOIUpdateNotify\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12*\n" +
	"\bentities\x18\x03 \x03(\v2\x0e.mapsvr.EntityR\bentities\x12\x1f\n" +
	"\vremoved_ids\x18\x04 \x03(\x05R\n" +
	"removedIds\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestampB.Z,pitaya-game/protos/protobuf/pb/golang/mapsvrb\x06proto3"

var (
	file_mapsvr_bigmap_proto_rawDescOnce sync.Once
	file_mapsvr_bigmap_proto_rawDescData []byte
)

func file_mapsvr_bigmap_proto_rawDescGZIP() []byte {
	file_mapsvr_bigmap_proto_rawDescOnce.Do(func() {
		file_mapsvr_bigmap_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mapsvr_bigmap_proto_rawDesc), len(file_mapsvr_bigmap_proto_rawDesc)))
	})
	return file_mapsvr_bigmap_proto_rawDescData
}

var file_mapsvr_bigmap_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_mapsvr_bigmap_proto_goTypes = []any{
	(*Position)(nil),              // 0: mapsvr.Position
	(*Size)(nil),                  // 1: mapsvr.Size
	(*EnterMapRequest)(nil),       // 2: mapsvr.EnterMapRequest
	(*EnterMapResponse)(nil),      // 3: mapsvr.EnterMapResponse
	(*MoveViewRequest)(nil),       // 4: mapsvr.MoveViewRequest
	(*MoveViewResponse)(nil),      // 5: mapsvr.MoveViewResponse
	(*LeaveMapRequest)(nil),       // 6: mapsvr.LeaveMapRequest
	(*LeaveMapResponse)(nil),      // 7: mapsvr.LeaveMapResponse
	(*Entity)(nil),                // 8: mapsvr.Entity
	(*EntityStatus)(nil),          // 9: mapsvr.EntityStatus
	(*BornTime)(nil),              // 10: mapsvr.BornTime
	(*LowHealthTime)(nil),         // 11: mapsvr.LowHealthTime
	(*DeadTime)(nil),              // 12: mapsvr.DeadTime
	(*Grid)(nil),                  // 13: mapsvr.Grid
	(*AOIUpdateNotify)(nil),       // 14: mapsvr.AOIUpdateNotify
	(*types.CommonResp)(nil),      // 15: types.CommonResp
	(*anypb.Any)(nil),             // 16: google.protobuf.Any
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
}
var file_mapsvr_bigmap_proto_depIdxs = []int32{
	0,  // 0: mapsvr.EnterMapRequest.position:type_name -> mapsvr.Position
	1,  // 1: mapsvr.EnterMapRequest.size:type_name -> mapsvr.Size
	15, // 2: mapsvr.EnterMapResponse.resp:type_name -> types.CommonResp
	0,  // 3: mapsvr.MoveViewRequest.center:type_name -> mapsvr.Position
	1,  // 4: mapsvr.MoveViewRequest.size:type_name -> mapsvr.Size
	15, // 5: mapsvr.MoveViewResponse.resp:type_name -> types.CommonResp
	15, // 6: mapsvr.LeaveMapResponse.resp:type_name -> types.CommonResp
	16, // 7: mapsvr.Entity.data:type_name -> google.protobuf.Any
	0,  // 8: mapsvr.Entity.pos:type_name -> mapsvr.Position
	17, // 9: mapsvr.BornTime.time:type_name -> google.protobuf.Timestamp
	17, // 10: mapsvr.LowHealthTime.time:type_name -> google.protobuf.Timestamp
	17, // 11: mapsvr.DeadTime.time:type_name -> google.protobuf.Timestamp
	0,  // 12: mapsvr.Grid.pos:type_name -> mapsvr.Position
	8,  // 13: mapsvr.AOIUpdateNotify.entities:type_name -> mapsvr.Entity
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_mapsvr_bigmap_proto_init() }
func file_mapsvr_bigmap_proto_init() {
	if File_mapsvr_bigmap_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mapsvr_bigmap_proto_rawDesc), len(file_mapsvr_bigmap_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mapsvr_bigmap_proto_goTypes,
		DependencyIndexes: file_mapsvr_bigmap_proto_depIdxs,
		MessageInfos:      file_mapsvr_bigmap_proto_msgTypes,
	}.Build()
	File_mapsvr_bigmap_proto = out.File
	file_mapsvr_bigmap_proto_goTypes = nil
	file_mapsvr_bigmap_proto_depIdxs = nil
}
