// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.2
// source: mapsvr/bigmapbattle.proto

package mapsvr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "pitaya-game/protos/protobuf/pb/golang/common/errors"
	types "pitaya-game/protos/protobuf/pb/golang/common/types"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TroopType int32

const (
	TroopType_TROOP_TYPE_UNSPECIFIED TroopType = 0
	TroopType_INFANTRY               TroopType = 1 // 步兵
	TroopType_CAVALRY                TroopType = 2 // 骑兵
	TroopType_ARCHER                 TroopType = 3 // 弓兵
)

// Enum value maps for TroopType.
var (
	TroopType_name = map[int32]string{
		0: "TROOP_TYPE_UNSPECIFIED",
		1: "INFANTRY",
		2: "CAVALRY",
		3: "ARCHER",
	}
	TroopType_value = map[string]int32{
		"TROOP_TYPE_UNSPECIFIED": 0,
		"INFANTRY":               1,
		"CAVALRY":                2,
		"ARCHER":                 3,
	}
)

func (x TroopType) Enum() *TroopType {
	p := new(TroopType)
	*p = x
	return p
}

func (x TroopType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TroopType) Descriptor() protoreflect.EnumDescriptor {
	return file_mapsvr_bigmapbattle_proto_enumTypes[0].Descriptor()
}

func (TroopType) Type() protoreflect.EnumType {
	return &file_mapsvr_bigmapbattle_proto_enumTypes[0]
}

func (x TroopType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TroopType.Descriptor instead.
func (TroopType) EnumDescriptor() ([]byte, []int) {
	return file_mapsvr_bigmapbattle_proto_rawDescGZIP(), []int{0}
}

type BattleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleRequest) Reset() {
	*x = BattleRequest{}
	mi := &file_mapsvr_bigmapbattle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleRequest) ProtoMessage() {}

func (x *BattleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapbattle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleRequest.ProtoReflect.Descriptor instead.
func (*BattleRequest) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapbattle_proto_rawDescGZIP(), []int{0}
}

type FighterInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"` //name ?
	X             int32                  `protobuf:"varint,2,opt,name=x,proto3" json:"x,omitempty"`                              // X坐标
	Y             int32                  `protobuf:"varint,3,opt,name=y,proto3" json:"y,omitempty"`                              // Y坐标
	SoldierCount  int32                  `protobuf:"varint,4,opt,name=soldier_count,json=soldierCount,proto3" json:"soldier_count,omitempty"`
	DeathCount    int32                  `protobuf:"varint,5,opt,name=death_count,json=deathCount,proto3" json:"death_count,omitempty"`
	LiveCount     int32                  `protobuf:"varint,6,opt,name=live_count,json=liveCount,proto3" json:"live_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FighterInfo) Reset() {
	*x = FighterInfo{}
	mi := &file_mapsvr_bigmapbattle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FighterInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FighterInfo) ProtoMessage() {}

func (x *FighterInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapbattle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FighterInfo.ProtoReflect.Descriptor instead.
func (*FighterInfo) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapbattle_proto_rawDescGZIP(), []int{1}
}

func (x *FighterInfo) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *FighterInfo) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *FighterInfo) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *FighterInfo) GetSoldierCount() int32 {
	if x != nil {
		return x.SoldierCount
	}
	return 0
}

func (x *FighterInfo) GetDeathCount() int32 {
	if x != nil {
		return x.DeathCount
	}
	return 0
}

func (x *FighterInfo) GetLiveCount() int32 {
	if x != nil {
		return x.LiveCount
	}
	return 0
}

type BattleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *types.CommonResp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	Attacker      *FighterInfo           `protobuf:"bytes,2,opt,name=attacker,proto3" json:"attacker,omitempty"`
	Defencer      *FighterInfo           `protobuf:"bytes,3,opt,name=defencer,proto3" json:"defencer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleResponse) Reset() {
	*x = BattleResponse{}
	mi := &file_mapsvr_bigmapbattle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleResponse) ProtoMessage() {}

func (x *BattleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapbattle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleResponse.ProtoReflect.Descriptor instead.
func (*BattleResponse) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapbattle_proto_rawDescGZIP(), []int{2}
}

func (x *BattleResponse) GetResp() *types.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *BattleResponse) GetAttacker() *FighterInfo {
	if x != nil {
		return x.Attacker
	}
	return nil
}

func (x *BattleResponse) GetDefencer() *FighterInfo {
	if x != nil {
		return x.Defencer
	}
	return nil
}

type TroopLevels struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LevelCounts   map[int32]int32        `protobuf:"bytes,1,rep,name=level_counts,json=levelCounts,proto3" json:"level_counts,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TroopLevels) Reset() {
	*x = TroopLevels{}
	mi := &file_mapsvr_bigmapbattle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TroopLevels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TroopLevels) ProtoMessage() {}

func (x *TroopLevels) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapbattle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TroopLevels.ProtoReflect.Descriptor instead.
func (*TroopLevels) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapbattle_proto_rawDescGZIP(), []int{3}
}

func (x *TroopLevels) GetLevelCounts() map[int32]int32 {
	if x != nil {
		return x.LevelCounts
	}
	return nil
}

type StartMarchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	X     int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`                      // X坐标
	Y     int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`                      // Y坐标
	FromX int32                  `protobuf:"varint,3,opt,name=from_x,json=fromX,proto3" json:"from_x,omitempty"` //临时加的出发坐标 未来这个值应该从服务器读取
	FromY int32                  `protobuf:"varint,4,opt,name=from_y,json=fromY,proto3" json:"from_y,omitempty"`
	// repeated TroopInfo troops = 5; // 行军兵力信息
	Troops        map[int32]*TroopLevels `protobuf:"bytes,5,rep,name=troops,proto3" json:"troops,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartMarchRequest) Reset() {
	*x = StartMarchRequest{}
	mi := &file_mapsvr_bigmapbattle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartMarchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMarchRequest) ProtoMessage() {}

func (x *StartMarchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapbattle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMarchRequest.ProtoReflect.Descriptor instead.
func (*StartMarchRequest) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapbattle_proto_rawDescGZIP(), []int{4}
}

func (x *StartMarchRequest) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *StartMarchRequest) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *StartMarchRequest) GetFromX() int32 {
	if x != nil {
		return x.FromX
	}
	return 0
}

func (x *StartMarchRequest) GetFromY() int32 {
	if x != nil {
		return x.FromY
	}
	return 0
}

func (x *StartMarchRequest) GetTroops() map[int32]*TroopLevels {
	if x != nil {
		return x.Troops
	}
	return nil
}

type StartMarchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          *types.CommonResp      `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	MarchDuration int32                  `protobuf:"varint,2,opt,name=march_duration,json=marchDuration,proto3" json:"march_duration,omitempty"` //行军所需时长（秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartMarchResponse) Reset() {
	*x = StartMarchResponse{}
	mi := &file_mapsvr_bigmapbattle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartMarchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMarchResponse) ProtoMessage() {}

func (x *StartMarchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mapsvr_bigmapbattle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMarchResponse.ProtoReflect.Descriptor instead.
func (*StartMarchResponse) Descriptor() ([]byte, []int) {
	return file_mapsvr_bigmapbattle_proto_rawDescGZIP(), []int{5}
}

func (x *StartMarchResponse) GetResp() *types.CommonResp {
	if x != nil {
		return x.Resp
	}
	return nil
}

func (x *StartMarchResponse) GetMarchDuration() int32 {
	if x != nil {
		return x.MarchDuration
	}
	return 0
}

var File_mapsvr_bigmapbattle_proto protoreflect.FileDescriptor

const file_mapsvr_bigmapbattle_proto_rawDesc = "" +
	"\n" +
	"\x19mapsvr/bigmapbattle.proto\x12\x06mapsvr\x1a\x18common/types/types.proto\x1a\x1acommon/errors/errors.proto\"\x0f\n" +
	"\rBattleRequest\"\xab\x01\n" +
	"\vFighterInfo\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\f\n" +
	"\x01x\x18\x02 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x05R\x01y\x12#\n" +
	"\rsoldier_count\x18\x04 \x01(\x05R\fsoldierCount\x12\x1f\n" +
	"\vdeath_count\x18\x05 \x01(\x05R\n" +
	"deathCount\x12\x1d\n" +
	"\n" +
	"live_count\x18\x06 \x01(\x05R\tliveCount\"\x99\x01\n" +
	"\x0eBattleResponse\x12%\n" +
	"\x04resp\x18\x01 \x01(\v2\x11.types.CommonRespR\x04resp\x12/\n" +
	"\battacker\x18\x02 \x01(\v2\x13.mapsvr.FighterInfoR\battacker\x12/\n" +
	"\bdefencer\x18\x03 \x01(\v2\x13.mapsvr.FighterInfoR\bdefencer\"\x96\x01\n" +
	"\vTroopLevels\x12G\n" +
	"\flevel_counts\x18\x01 \x03(\v2$.mapsvr.TroopLevels.LevelCountsEntryR\vlevelCounts\x1a>\n" +
	"\x10LevelCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\xec\x01\n" +
	"\x11StartMarchRequest\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x15\n" +
	"\x06from_x\x18\x03 \x01(\x05R\x05fromX\x12\x15\n" +
	"\x06from_y\x18\x04 \x01(\x05R\x05fromY\x12=\n" +
	"\x06troops\x18\x05 \x03(\v2%.mapsvr.StartMarchRequest.TroopsEntryR\x06troops\x1aN\n" +
	"\vTroopsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.mapsvr.TroopLevelsR\x05value:\x028\x01\"b\n" +
	"\x12StartMarchResponse\x12%\n" +
	"\x04resp\x18\x01 \x01(\v2\x11.types.CommonRespR\x04resp\x12%\n" +
	"\x0emarch_duration\x18\x02 \x01(\x05R\rmarchDuration*N\n" +
	"\tTroopType\x12\x1a\n" +
	"\x16TROOP_TYPE_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bINFANTRY\x10\x01\x12\v\n" +
	"\aCAVALRY\x10\x02\x12\n" +
	"\n" +
	"\x06ARCHER\x10\x03B.Z,pitaya-game/protos/protobuf/pb/golang/mapsvrb\x06proto3"

var (
	file_mapsvr_bigmapbattle_proto_rawDescOnce sync.Once
	file_mapsvr_bigmapbattle_proto_rawDescData []byte
)

func file_mapsvr_bigmapbattle_proto_rawDescGZIP() []byte {
	file_mapsvr_bigmapbattle_proto_rawDescOnce.Do(func() {
		file_mapsvr_bigmapbattle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mapsvr_bigmapbattle_proto_rawDesc), len(file_mapsvr_bigmapbattle_proto_rawDesc)))
	})
	return file_mapsvr_bigmapbattle_proto_rawDescData
}

var file_mapsvr_bigmapbattle_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mapsvr_bigmapbattle_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_mapsvr_bigmapbattle_proto_goTypes = []any{
	(TroopType)(0),             // 0: mapsvr.TroopType
	(*BattleRequest)(nil),      // 1: mapsvr.BattleRequest
	(*FighterInfo)(nil),        // 2: mapsvr.FighterInfo
	(*BattleResponse)(nil),     // 3: mapsvr.BattleResponse
	(*TroopLevels)(nil),        // 4: mapsvr.TroopLevels
	(*StartMarchRequest)(nil),  // 5: mapsvr.StartMarchRequest
	(*StartMarchResponse)(nil), // 6: mapsvr.StartMarchResponse
	nil,                        // 7: mapsvr.TroopLevels.LevelCountsEntry
	nil,                        // 8: mapsvr.StartMarchRequest.TroopsEntry
	(*types.CommonResp)(nil),   // 9: types.CommonResp
}
var file_mapsvr_bigmapbattle_proto_depIdxs = []int32{
	9, // 0: mapsvr.BattleResponse.resp:type_name -> types.CommonResp
	2, // 1: mapsvr.BattleResponse.attacker:type_name -> mapsvr.FighterInfo
	2, // 2: mapsvr.BattleResponse.defencer:type_name -> mapsvr.FighterInfo
	7, // 3: mapsvr.TroopLevels.level_counts:type_name -> mapsvr.TroopLevels.LevelCountsEntry
	8, // 4: mapsvr.StartMarchRequest.troops:type_name -> mapsvr.StartMarchRequest.TroopsEntry
	9, // 5: mapsvr.StartMarchResponse.resp:type_name -> types.CommonResp
	4, // 6: mapsvr.StartMarchRequest.TroopsEntry.value:type_name -> mapsvr.TroopLevels
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_mapsvr_bigmapbattle_proto_init() }
func file_mapsvr_bigmapbattle_proto_init() {
	if File_mapsvr_bigmapbattle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mapsvr_bigmapbattle_proto_rawDesc), len(file_mapsvr_bigmapbattle_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mapsvr_bigmapbattle_proto_goTypes,
		DependencyIndexes: file_mapsvr_bigmapbattle_proto_depIdxs,
		EnumInfos:         file_mapsvr_bigmapbattle_proto_enumTypes,
		MessageInfos:      file_mapsvr_bigmapbattle_proto_msgTypes,
	}.Build()
	File_mapsvr_bigmapbattle_proto = out.File
	file_mapsvr_bigmapbattle_proto_goTypes = nil
	file_mapsvr_bigmapbattle_proto_depIdxs = nil
}
