syntax = "proto3";

package mapsvr;
option go_package = "pitaya-game/protos/protobuf/pb/golang/mapsvr";

import "google/protobuf/any.proto";
import "google/protobuf/timestamp.proto";
// 导入公共类型
import "common/types/types.proto";
import "common/errors/errors.proto";

message Position {
  int32 x = 1;
  int32 y = 2;
}

message Size {
  int32 w = 1;
  int32 h = 2;
}

message EnterMapRequest {
  int32 layer = 1;
  // 视野中心点格子的左下角坐标
  Position position = 2;
  // 1.5屏幕格子数
  Size size = 3;
}
message EnterMapResponse {
  types.CommonResp resp = 1;
}

message MoveViewRequest {
  int32 layer = 1;
  Position center = 2;
  Size size = 3;
}
message MoveViewResponse {
  types.CommonResp resp = 1;
}

message LeaveMapRequest {
}
message LeaveMapResponse {
  types.CommonResp resp = 1;
}

// ------------------- Entity ------------------
message Entity {
  int32 id = 1;
  int32 config_id = 2;
  int32 type = 3;
  int32 sub_type = 4;
  repeated google.protobuf.Any data = 5;
  Position pos = 6;
  int64 version = 7;
  int32 gridId = 8;
}

message EntityStatus {
  bool IsTarget = 1;
}

message BornTime {
  google.protobuf.Timestamp time = 1;
}

message LowHealthTime {
  google.protobuf.Timestamp time = 1;
}

message DeadTime {
  google.protobuf.Timestamp time = 1;
}

// ------------------- Grid ------------------

message Grid {
  int32 id = 1;
  Position pos = 2;
  int64 version = 5;
  int32 entityId = 6;
}

message AOISnapshotNotify {
  Position pos = 1; // 分区坐标（横坐标x=(0,11) 纵坐标y=(0,11)）
  repeated Entity entities = 2; // 全量实体列表
  int64 timestamp = 3;
}

message AOIDeltaNotify {
  Position pos = 1; // 分区坐标（横坐标x=(0,11) 纵坐标y=(0,11)）
  repeated Entity entities = 2; // 增量新增或更新实体列表
  repeated int32 removed_ids = 3; // 增量中的实体移除ID列表
  int64 timestamp = 4;
}
